#!/usr/bin/env python3
"""One-off: export Tabel_Materi_per_Jenjang_Umur_per_Semester(1).xlsx into
internal/store/seed-data/kurikulum.sql (tingkat + materi_ajar INSERTs).

Run:  python3 scripts/export-kurikulum.py [path-to-xlsx] > internal/store/seed-data/kurikulum.sql
"""
import sys
import zipfile
import xml.etree.ElementTree as ET

NS = "{http://schemas.openxmlformats.org/spreadsheetml/2006/main}"


def cell_value(c, sst):
    t = c.get("t")
    if t == "inlineStr":
        return "".join(x.text or "" for x in c.iter(NS + "t")).strip()
    v = c.find(NS + "v")
    if v is None or v.text is None:
        return ""
    if t == "s":
        return sst[int(v.text)].strip()
    return v.text.strip()


def main(path):
    z = zipfile.ZipFile(path)
    sst = []
    try:
        for si in ET.fromstring(z.read("xl/sharedStrings.xml")):
            sst.append("".join(t.text or "" for t in si.iter(NS + "t")))
    except KeyError:
        pass

    wb = ET.fromstring(z.read("xl/workbook.xml"))
    rels = {
        r.get("Id"): r.get("Target")
        for r in ET.fromstring(z.read("xl/_rels/workbook.xml.rels"))
    }
    sheets = []
    for s in wb.find(NS + "sheets"):
        rid = s.get("{http://schemas.openxmlformats.org/officeDocument/2006/relationships}id")
        tgt = rels[rid].lstrip("/")
        if not tgt.startswith("xl/"):
            tgt = "xl/" + tgt
        sheets.append((s.get("name"), tgt))

    HEADERS = ["No", "No Sumber", "Tema", "Sub Tema", "Rincian", "Materi",
               "Cakupan", "Jenis Materi", "Target Semester Ini",
               "Deskripsi Isi", "Status Promes", "Keterangan"]

    tingkat_rows = []   # (nama, umur, urutan)
    materi_rows = []    # dicts
    seq = 0

    for name, path in sheets:
        if name == "Ringkasan":
            continue
        root = ET.fromstring(z.read(path))
        rows = [[cell_value(c, sst) for c in row.findall(NS + "c")] for row in root.iter(NS + "row")]
        rows = [r for r in rows if any(r)]
        if not rows:
            continue  # Tanpa Tanda Semester is empty

        title = rows[0][0] if rows else ""
        m = __import__("re").search(r"JENJANG UMUR\s+(.+?)\s+TAHUN", title)
        if not m:
            print(f"// skip sheet {name}: no JENJANG UMUR in title", file=sys.stderr)
            continue
        age_txt = m.group(1)  # e.g. "≤ 6" or "7"
        umur = None
        if "≤" in age_txt:
            umur = int(age_txt.replace("≤", "").strip())
        elif age_txt.isdigit():
            umur = int(age_txt)

        urutan = len(tingkat_rows) + 1
        nama = {"≤ 6": "≤6 Tahun"}.get(age_txt, age_txt + " Tahun") if umur else age_txt + " Tahun"
        tingkat_rows.append((nama, umur, urutan))
        tk_id = f"tk-{urutan:02d}"

        semester = None
        for r in rows:
            a = r[0]
            if a.startswith("SEMESTER 1"):
                semester = 1
                continue
            if a.startswith("SEMESTER 2"):
                semester = 2
                continue
            if r[:2] == HEADERS[:2] or (r and r[0] == "No" and len(r) > 1 and r[1] == "No Sumber"):
                continue
            if not a.isdigit() or semester is None:
                continue
            nomor = int(a)
            if len(r) < 6:
                continue
            seq += 1
            jenis = r[7] if len(r) > 7 else ""
            if not jenis:
                jenis = "baru"
            jenis = {"Baru": "baru", "Lanjutan": "lanjutan", "Mengulang": "mengulang"}.get(jenis.strip(), "baru")
            materi_rows.append({
                "id": f"ma-{seq:05d}",
                "tk": tk_id,
                "nomor": nomor,
                "sumber_no": int(r[1]) if r[1].isdigit() else None,
                "tema": r[2],
                "sub_tema": r[3],
                "rincian": r[4],
                "materi": r[5],
                "cakupan": r[6] if len(r) > 6 else "",
                "jenis": jenis,
                "target": r[8] if len(r) > 8 else "",
                "deskripsi": r[9] if len(r) > 9 else "",
                "status_promes": r[10] if len(r) > 10 else "",
                "keterangan": r[11] if len(r) > 11 else "",
                "semester": semester,
            })

    def q(v):
        if v is None:
            return "NULL"
        return "'" + str(v).replace("'", "''") + "'"

    out = []
    out.append("-- Generated by scripts/export-kurikulum.py — DO NOT EDIT BY HAND.")
    out.append(f"-- Source: Tabel_Materi_per_Jenjang_Umur_per_Semester(1).xlsx ({len(tingkat_rows)} tingkat, {len(materi_rows)} materi)")
    for nama, umur, urutan in tingkat_rows:
        out.append(
            f"INSERT INTO tingkat (id, nama, urutan, umur) VALUES ({q(f'tk-{urutan:02d}')}, {q(nama)}, {urutan}, {q(umur)});"
        )
    for m in materi_rows:
        out.append(
            "INSERT INTO materi_ajar (id, tingkat_id, nomor, sumber_no, tema, sub_tema, rincian, materi, cakupan, jenis, target_semester, deskripsi, status_promes, keterangan, semester) VALUES ("
            + ", ".join([
                q(m["id"]), q(m["tk"]), str(m["nomor"]), q(m["sumber_no"]),
                q(m["tema"]), q(m["sub_tema"]), q(m["rincian"]), q(m["materi"]),
                q(m["cakupan"]), q(m["jenis"]), q(m["target"]), q(m["deskripsi"]),
                q(m["status_promes"]), q(m["keterangan"]), q(m["semester"]),
            ]) + ");"
        )
    print("\n".join(out))
    print(f"// {len(tingkat_rows)} tingkat, {len(materi_rows)} materi_ajar", file=sys.stderr)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "/home/anchor/Podman/cai/Tabel_Materi_per_Jenjang_Umur_per_Semester(1).xlsx")
